db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cfmy?characterEncoding=utf-8
  username: root
  password: zw200813

mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.zw.dao.entity
jdbc:
  type: mysql
spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driverClassName: ${db.driverClassName}
    #type: com.zaxxer.hikari.HikariDataSource
    maxPoolSize: 30
