db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cfmy?characterEncoding=utf-8
  username: root
  password: zw200813
  model: com.zw.model
  mapper: com.zw.mapper
  xml: mybatis.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: ${db.driverClassName}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    maxPoolSize: 30
  jooq:
    sql-dialect: POSTGRES

